= Mapping Extension API
:toc: auto

The Eclipse JNoSQL Mapping Extension API is a collection of implementations/specializations from the https://jakarta.ee/specifications/nosql/[Jakarta NoSQL] specification that defines specific behavior in various NoSQL databases.

== Graph Connections

Graph connections is a project that contains several `GraphConfiguration` implementations.

[source,xml]
----
<dependency>
  <groupId>org.eclipse.jnosql.mapping</groupId>
  <artifactId>jnosql-jnosql-graph-connections</artifactId>
  <version>1.0.0-b6</version>
</dependency>
----

=== ArangoDB


[cols="ArangoDB Properties"]
|===
|Configuration property |Description

|`jnosql.arangodb.graph.edge`
|The edge collection. It uses as a prefix. E.g.:jnosql.arangodb.graph.edge.1=edge

|`jnosql.arangodb.graph.relationship`
|Edge collection, the source vertex collection and the target vertex collection split by pipe. It hou,It uses as a prefix. E.g.: jnosql.arangodb.graph.relationship.1=Person\|knows\|Person

|`jnosql.arangodb.graph.vertex`
|The vertex collection. It uses as a prefix. E.g.: jnosql.arangodb.graph.vertex.1=vertex

|`jnosql.arangodb.graph.graph`
|Name of the graph to use.

|`jnosql.arangodb.graph.host`
|The database host.

|`jnosql.arangodb.graph.user`
|The user's credential.

|`jnosql.arangodb.graph.password`
|The password's credential.

|===

This is an example using ArangoDB's Graph API with MicroProfile Config.

[source,properties]
----
jnosql.graph.provider=org.eclipse.jnosql.mapping.graph.connections.ArangoDBGraphConfiguration
jnosql.arangodb.graph.graph=marketing
jnosql.arangodb.graph.vertex.1=Person
jnosql.arangodb.graph.edge.1=knows
jnosql.arangodb.graph.relationship.1=Person|knows|Person
----

=== Janus

This is an example using Janus's Graph API with MicroProfile Config.

WARNING: The API will pass and use the properties from `org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration`
[source,properties]
----
jnosql.graph.provider=org.eclipse.jnosql.mapping.graph.connections.JanusGraphConfiguration
graphname=name
allow-upgrade=false
----

=== Titan

This is an example using Titan's Graph API with MicroProfile Config.

WARNING: The API will pass and use the properties from `com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration`
[source,properties]
----
jnosql.graph.provider=org.eclipse.jnosql.mapping.graph.connections.TitanGraphConfiguration
----

=== Neo4j

[cols="Neo4j Properties"]
|===
|Configuration property |Description

|`jnosql.neo4j.host`
|The database host. Default: "bolt://localhost:7687"

|`jnosql.neo4j.user`
|The user's credential. Default: "neo4j"

|`jnosql.neo4j.password`
|The password's credential. Default: "neo4j"

|===

This is an example using Neo4J's Graph API with MicroProfile Config.

[source,properties]
----
jnosql.graph.provider=org.eclipse.jnosql.mapping.graph.connections.Neo4JGraphConfiguration
jnosql.neo4j.user=neo4j
jnosql.neo4j.password=neo4j
jnosql.neo4j.host=bolt://localhost:7687
----

=== Neo4j Remote

[cols="Neo4j Remote Properties"]
|===
|Configuration property |Description

|`jnosql.neo4j.host`
|The database host. Default: "bolt://localhost:7687"

|===

This is an example using Neo4J's Graph API with MicroProfile Config.

[source,properties]
----
jnosql.graph.provider=org.eclipse.jnosql.mapping.graph.connections.Neo4JEmbeddedGraphConfiguration
jnosql.neo4j.host=/home/otaviojava/data/
----

== CriteriaQuery API 

This is the experimental Criteria API, largely inspired by the JPA one.
Using this API you can execute queries built via CriteriaQuery.
The CriteriaQuery is used in combination with Metamodel Attributes.
These attributes are automagically generated from the defined NoSQL Entities.

The Criteria API can be used via CriteriaDocumentTemplate.

=== Set dependency


[source,xml]
----
  <dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>jnosql-metamodel-processor-extension</artifactId>
    <version>1.0.0-b6</version>
    <optional>true</optional>
  </dependency>
  <dependency>
      <groupId>org.eclipse.jnosql.mapping</groupId>
      <artifactId>jnosql-criteria-extension</artifactId>
      <version>1.0.0-b6</version>
  </dependency>
----

=== Create a CriteriaDocumentTemplate

[source,java]
----
    @Inject
    private CriteriaDocumentTemplateProducer producer;

    @Inject
    private DocumentManager documentManager;
----

[source,java]
----
    CriteriaDocumentTemplate template = producer.get(documentManager);
----

=== EntityQuery

You can fetch entities with an EntityQuery :

[source,java]
----
CriteriaQuery<Person> personQuery = template.createQuery(Person.class);

EntityQueryResult<Person> executeQuery = template.executeQuery(
        personQuery.select().where(
                personQuery.from().get(
                        Person_.name
                ).equal(
                        "Poliana"
                ).or(
                        personQuery.from().get(
                                Person_.age
                        ).greaterThanOrEqualTo(17)
                )
        )
);

Stream<Person> stream = executeQuery.getEntities();
----

=== ExpressionQuery

You can fetch single columns/projections using an ExpressionQuery :

[source,java]
----
CriteriaQuery<Person> personQuery = template.createQuery(Person.class);

StringExpression<Person, Person> nameExpression = personQuery.from().get(
        Person_.name
);
NumberExpression<Person, Person, Integer> ageExpression = personQuery.from().get(
        Person_.age
);

ExpressionQueryResult<Person> executeQuery = template.executeQuery(
        personQuery.select(
                nameExpression,
                ageExpression
        ).where(
                nameExpression.equal(
                        "Poliana"
                ).or(
                        ageExpression.greaterThanOrEqualTo(17)
                )
        )
);

Optional<ExpressionQueryResultRow<Person>> findFirst = executeQuery.getRows().findFirst();

String name = findFirst.get().get(
        nameExpression
);

Integer age = findFirst.get().get(
        ageExpression
);

----


== Contributing

We are very happy you are interested in helping us and there are plenty ways you can do so.

- https://github.com/eclipse/jnosql/issues[**Open an Issue:**]  Recommend improvements, changes and report bugs

- **Open a Pull Request:** If you feel like you can even make changes to our source code and suggest them, just check out our link:CONTRIBUTING.adoc[contributing guide] to learn about the development process, how to suggest bugfixes and improvements.


